spring:
  datasource:
    url: jdbc:postgresql:///postgres
    username: user
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    properties:
      hibernate:
        jdbc:
          batch_size: 1000
        order_inserts: true

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG