INSERT INTO dishes (name, cuisine) VALUES
                                       ('Spaghetti Carbonara', 'Italian'),
                                       ('Sushi', 'Japanese'),
                                       ('Tacos', 'Mexican'),
                                       ('Beef Stroganoff', 'Russian'),
                                       ('Kimchi', 'Korean'),
                                       ('Butter Chicken', 'Indian'),
                                       ('Croissant', 'French'),
                                       ('French fries', 'Belgian'),
                                       ('Potato Pancake', 'Belarus')
